var DOC = window.DOC = {
    categorias: [],
    topicos: [],
    versoes: [],
    glossario: [],
    faq: [],
    temasFaq: [],

    topico: function (t) { this.topicos.push(t); },
    versao: function (v) { this.versoes.push(v); },
    termo: function (g) { this.glossario.push(g); },
    pergunta: function (f) { this.faq.push(f); }
};

DOC.categorias = [
    { id: 'fundamentos', icone: 'livro',
      pt: { nome: 'Fundamentos', desc: 'O que é o APEX, arquitetura, workspaces, sessões e os conceitos que sustentam tudo.' },
      en: { nome: 'Fundamentals', desc: 'What APEX is, architecture, workspaces, sessions and the core concepts behind everything.' } },
    { id: 'instalacao', icone: 'servidor',
      pt: { nome: 'Instalação & Administração', desc: 'Instalar, atualizar e administrar: ORDS, patches, instância, workspaces e nuvem.' },
      en: { nome: 'Installation & Administration', desc: 'Install, upgrade and administer: ORDS, patches, instance, workspaces and cloud.' } },
    { id: 'app-builder', icone: 'camadas',
      pt: { nome: 'App Builder & Páginas', desc: 'Criação de apps, Page Designer, componentes compartilhados, navegação e páginas.' },
      en: { nome: 'App Builder & Pages', desc: 'Creating apps, Page Designer, shared components, navigation and pages.' } },
    { id: 'componentes', icone: 'grade',
      pt: { nome: 'Regiões & Relatórios', desc: 'Interactive Report, Interactive Grid, Cards, Charts, Maps, Calendar, Faceted Search e mais.' },
      en: { nome: 'Regions & Reports', desc: 'Interactive Report, Interactive Grid, Cards, Charts, Maps, Calendar, Faceted Search and more.' } },
    { id: 'itens', icone: 'formulario',
      pt: { nome: 'Itens, Forms & Validações', desc: 'Tipos de item, LOVs, formulários, session state, computações e validações.' },
      en: { nome: 'Items, Forms & Validations', desc: 'Item types, LOVs, forms, session state, computations and validations.' } },
    { id: 'dinamico', icone: 'raio',
      pt: { nome: 'Dynamic Actions & JavaScript', desc: 'Ações dinâmicas, API JavaScript, chamadas AJAX e interatividade no navegador.' },
      en: { nome: 'Dynamic Actions & JavaScript', desc: 'Dynamic actions, JavaScript API, AJAX calls and browser-side interactivity.' } },
    { id: 'plsql', icone: 'codigo',
      pt: { nome: 'SQL, PL/SQL & APIs', desc: 'Pacotes APEX_*, processos, collections, APEX_EXEC, JSON e utilidades do dia a dia.' },
      en: { nome: 'SQL, PL/SQL & APIs', desc: 'APEX_* packages, processes, collections, APEX_EXEC, JSON and everyday utilities.' } },
    { id: 'seguranca', icone: 'escudo',
      pt: { nome: 'Segurança', desc: 'Autenticação, autorização, Session State Protection, escaping, CSP e boas práticas.' },
      en: { nome: 'Security', desc: 'Authentication, authorization, Session State Protection, escaping, CSP and best practices.' } },
    { id: 'integracao', icone: 'plugue',
      pt: { nome: 'REST & Integrações', desc: 'REST Data Sources, ORDS, credenciais web, carga e sincronização de dados.' },
      en: { nome: 'REST & Integrations', desc: 'REST Data Sources, ORDS, web credentials, data loading and synchronization.' } },
    { id: 'ui', icone: 'paleta',
      pt: { nome: 'Interface, Temas & PWA', desc: 'Universal Theme, Theme Roller, Template Components, acessibilidade e Progressive Web Apps.' },
      en: { nome: 'UI, Themes & PWA', desc: 'Universal Theme, Theme Roller, Template Components, accessibility and Progressive Web Apps.' } },
    { id: 'ia', icone: 'brilho',
      pt: { nome: 'IA Generativa', desc: 'APEX Assistant, serviços de IA generativa, APEX_AI, RAG, Select AI e geração de apps.' },
      en: { nome: 'Generative AI', desc: 'APEX Assistant, generative AI services, APEX_AI, RAG, Select AI and app generation.' } },
    { id: 'processos', icone: 'fluxo',
      pt: { nome: 'Workflow & Automação', desc: 'Human Tasks e aprovações, Workflow, Automations, execução em background, e-mail e push.' },
      en: { nome: 'Workflow & Automation', desc: 'Human Tasks and approvals, Workflow, Automations, background execution, e-mail and push.' } },
    { id: 'devops', icone: 'foguete',
      pt: { nome: 'Ciclo de vida & DevOps', desc: 'Exportar, importar, Working Copies, controle de versão, SQLcl Projects e CI/CD.' },
      en: { nome: 'Lifecycle & DevOps', desc: 'Export, import, Working Copies, version control, SQLcl Projects and CI/CD.' } },
    { id: 'globalizacao', icone: 'globo',
      pt: { nome: 'Globalização', desc: 'Tradução de aplicações, idiomas, formatos de data e número, fusos horários.' },
      en: { nome: 'Globalization', desc: 'Application translation, languages, date and number formats, time zones.' } },
    { id: 'performance', icone: 'velocimetro',
      pt: { nome: 'Performance & Debug', desc: 'Modo debug, APEX_DEBUG, Advisor, monitoramento e ajuste de performance.' },
      en: { nome: 'Performance & Debugging', desc: 'Debug mode, APEX_DEBUG, Advisor, monitoring and performance tuning.' } },
    { id: 'boas-praticas', icone: 'estrela',
      pt: { nome: 'Boas práticas', desc: 'Arquitetura de código, padrões de nomenclatura, reutilização e checklist de qualidade.' },
      en: { nome: 'Best Practices', desc: 'Code architecture, naming conventions, reuse and a quality checklist.' } }
];

DOC.eras = [
    { id: 'origens',  pt: 'Origens & HTML DB',             en: 'Origins & HTML DB',              anos: '1999–2005' },
    { id: 'classica', pt: 'Application Express 2.x–4.x',   en: 'Application Express 2.x–4.x',    anos: '2006–2015' },
    { id: 'moderna',  pt: 'APEX 5 e Universal Theme',      en: 'APEX 5 & Universal Theme',       anos: '2015–2017' },
    { id: 'anual',    pt: 'Numeração anual (18.1+)',       en: 'Year-based numbering (18.1+)',   anos: '2018–2023' },
    { id: 'ia',       pt: 'Era da IA',                     en: 'The AI era',                     anos: '2024+' }
];

DOC.temasFaq = [
    { id: 'geral',       pt: 'Geral & licenciamento',        en: 'General & licensing' },
    { id: 'instalacao',  pt: 'Instalação, ORDS & upgrade',   en: 'Installation, ORDS & upgrade' },
    { id: 'sessao',      pt: 'Itens & session state',        en: 'Items & session state' },
    { id: 'relatorios',  pt: 'Relatórios & Interactive Grid',en: 'Reports & Interactive Grid' },
    { id: 'dinamico',    pt: 'Dynamic Actions & JavaScript', en: 'Dynamic Actions & JavaScript' },
    { id: 'forms',       pt: 'Formulários & validações',     en: 'Forms & validations' },
    { id: 'arquivos',    pt: 'Arquivos, e-mail & PDF',       en: 'Files, e-mail & PDF' },
    { id: 'seguranca',   pt: 'Segurança & autenticação',     en: 'Security & authentication' },
    { id: 'integracao',  pt: 'REST & integrações',           en: 'REST & integrations' },
    { id: 'deploy',      pt: 'Deploy & ambientes',           en: 'Deployment & environments' },
    { id: 'ui',          pt: 'Interface & CSS',              en: 'UI & CSS' },
    { id: 'performance', pt: 'Performance & debug',          en: 'Performance & debugging' },
    { id: 'erros',       pt: 'Erros comuns',                 en: 'Common errors' },
    { id: 'ia',          pt: 'IA generativa',                en: 'Generative AI' },
    { id: 'carreira',    pt: 'Aprendizado & carreira',       en: 'Learning & career' }
];

DOC.sinonimos = {
    'ig': ['interactive grid', 'grade interativa'],
    'ir': ['interactive report', 'relatorio interativo'],
    'da': ['dynamic action', 'acao dinamica'],
    'acao dinamica': ['dynamic action'],
    'acoes dinamicas': ['dynamic action'],
    'lov': ['list of values', 'lista de valores'],
    'ords': ['oracle rest data services'],
    'ssp': ['session state protection'],
    'xss': ['cross site scripting', 'escape'],
    'sso': ['single sign on', 'social sign in', 'saml'],
    'pwa': ['progressive web app'],
    'ia': ['ai', 'inteligencia artificial', 'generative ai'],
    'ai': ['ia', 'inteligencia artificial', 'generative ai'],
    'llm': ['generative ai', 'apex_ai'],
    'grafico': ['chart'], 'graficos': ['chart'], 'chart': ['grafico'],
    'mapa': ['map'], 'map': ['mapa'],
    'calendario': ['calendar'], 'calendar': ['calendario'],
    'cartoes': ['cards'],
    'formulario': ['form'], 'form': ['formulario'],
    'relatorio': ['report'], 'report': ['relatorio'],
    'tema': ['theme'], 'theme': ['tema'],
    'traducao': ['translation'], 'translation': ['traducao'],
    'aprovacao': ['approval', 'human task'], 'approval': ['aprovacao'],
    'tarefa': ['task'],
    'fluxo': ['workflow'],
    'login': ['authentication', 'autenticacao'],
    'autenticacao': ['authentication'], 'authentication': ['autenticacao'],
    'autorizacao': ['authorization'], 'authorization': ['autorizacao'],
    'instalar': ['instalacao', 'install'], 'install': ['instalacao'],
    'atualizar': ['upgrade', 'patch'],
    'cicd': ['ci/cd', 'devops'],
    'git': ['controle de versao', 'version control', 'sqlcl'],
    'email': ['apex_mail', 'e-mail'], 'e-mail': ['apex_mail'],
    'pdf': ['print', 'document generator', 'impressao'],
    'impressao': ['print', 'pdf'],
    'json': ['apex_json'],
    'debug': ['depuracao', 'apex_debug'], 'depuracao': ['debug'],
    'lento': ['performance'], 'lentidao': ['performance'], 'slow': ['performance'],
    'gratis': ['free', 'licenca', 'custo'], 'free': ['gratis', 'license'],
    'preco': ['licenca', 'custo', 'license']
};
